# Generated by Django 3.1.4 on 2021-08-16 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('presupuesto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PresupuestoPersona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_analisis', models.CharField(max_length=300, unique=True)),
                ('observacion', models.TextField(null=True)),
                ('estado', models.CharField(blank=True, choices=[('1', 'Por revisar'), ('2', 'Aceptado'), ('3', 'Con observación')], default='1', max_length=1, verbose_name='Estado del registro')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='presupuesto.periodo')),
            ],
            options={
                'verbose_name': 'Presupuesto de personas',
                'verbose_name_plural': 'Presupuestos de personas',
            },
        ),
    ]
